export const SatelliteModel = [
  { "id": 1, "code": "AA", "name": "TURKSAT 3A", "longitude": "41.9° E" },
  {
    "id": 2,
    "code": "AB",
    "name": "METEOSAT 9 (MSG 2)",
    "longitude": "45.7° E"
  },
  { "id": 3, "code": "AC", "name": "TELECOM 2D", "longitude": "71.1° E" },
  { "id": 4, "code": "AD", "name": "COSMOS 2440", "longitude": "71.4° E" },
  {
    "id": 5,
    "code": "AE",
    "name": "EUTELSAT 1-F1 (ECS 1)",
    "longitude": "71.4° E"
  },
  { "id": 6, "code": "AF", "name": "RADUGA 30", "longitude": "71.6° E" },
  { "id": 7, "code": "AG", "name": "COSMOS 1540", "longitude": "71.6° E" },
  { "id": 8, "code": "AH", "name": "COSMOS 1961", "longitude": "71.7° E" },
  { "id": 9, "code": "AI", "name": "COSMOS 2133", "longitude": "71.8° E" },
  { "id": 10, "code": "AJ", "name": "COSMOS 2350", "longitude": "71.9° E" },
  { "id": 11, "code": "AK", "name": "RADUGA 32", "longitude": "71.9° E" },
  { "id": 12, "code": "AL", "name": "INTELSAT 22", "longitude": "72.1° E" },
  { "id": 13, "code": "AM", "name": "AZERSPACE 1", "longitude": "46° E" },
  { "id": 14, "code": "AN", "name": "EKRAN 20", "longitude": "72.2° E" },
  { "id": 15, "code": "AO", "name": "BS-3B (YURI 3B)", "longitude": "72.7° E" },
  { "id": 16, "code": "AP", "name": "XM-2", "longitude": "72.8° E" },
  { "id": 17, "code": "AQ", "name": "OPS 6063", "longitude": "73.2° E" },
  { "id": 18, "code": "AR", "name": "GSAT 11", "longitude": "73.9° E" },
  { "id": 19, "code": "AS", "name": "GSAT 18", "longitude": "74° E" },
  { "id": 20, "code": "AT", "name": "GSAT-14", "longitude": "74° E" },
  { "id": 21, "code": "AU", "name": "GSAT-7 (INSAT 4F)", "longitude": "74° E" },
  { "id": 22, "code": "AV", "name": "INSAT 3DR", "longitude": "74.1° E" },
  { "id": 23, "code": "AW", "name": "SIRIO", "longitude": "74.5° E" },
  { "id": 24, "code": "AX", "name": "BEIDOU 1C", "longitude": "46.9° E" },
  { "id": 25, "code": "AY", "name": "MUOS 4", "longitude": "74.7° E" },
  { "id": 26, "code": "AZ", "name": "ABS 2A", "longitude": "74.8° E" },
  { "id": 27, "code": "BA", "name": "ABS 2", "longitude": "74.9° E" },
  { "id": 28, "code": "BB", "name": "EKRAN 7", "longitude": "74.9° E" },
  { "id": 29, "code": "BC", "name": "APSTAR 7", "longitude": "76.5° E" },
  { "id": 30, "code": "BD", "name": "GALS 2", "longitude": "76.6° E" },
  { "id": 31, "code": "BE", "name": "COSMOS 1738", "longitude": "77.4° E" },
  { "id": 32, "code": "BF", "name": "LUCH 1", "longitude": "77.5° E" },
  {
    "id": 33,
    "code": "BG",
    "name": "HGS 4 (GALAXY 4)",
    "longitude": "77.7° E"
  },
  { "id": 34, "code": "BH", "name": "NIMIQ 1", "longitude": "77.9° E" },
  { "id": 35, "code": "BI", "name": "SYRACUSE 3A", "longitude": "46.9° E" },
  { "id": 36, "code": "BJ", "name": "INTELSAT 706", "longitude": "78.4° E" },
  { "id": 37, "code": "BK", "name": "THAICOM 8", "longitude": "78.4° E" },
  { "id": 38, "code": "BL", "name": "THAICOM 6", "longitude": "78.5° E" },
  { "id": 39, "code": "BM", "name": "FENGYUN 2H", "longitude": "79.1° E" },
  { "id": 40, "code": "BN", "name": "BEIDOU G3", "longitude": "79.5° E" },
  { "id": 41, "code": "BO", "name": "TIANLIAN 2-01", "longitude": "79.8° E" },
  { "id": 42, "code": "BP", "name": "COSMOS 2085", "longitude": "79.8° E" },
  {
    "id": 43,
    "code": "BQ",
    "name": "ESIAFI 1 (COMSTAR 4)",
    "longitude": "80° E"
  },
  { "id": 44, "code": "BR", "name": "BEIDOU 3 G2", "longitude": "80° E" },
  { "id": 45, "code": "BS", "name": "COSMOS 2371", "longitude": "80.2° E" },
  { "id": 46, "code": "BT", "name": "ECHOSTAR 4", "longitude": "47.4° E" },
  { "id": 47, "code": "BU", "name": "COSMOS 2513", "longitude": "80.2° E" },
  { "id": 48, "code": "BV", "name": "SYNCOM 2 (A 26)", "longitude": "80.4° E" },
  { "id": 49, "code": "BW", "name": "TELKOM 1", "longitude": "81.1° E" },
  { "id": 50, "code": "BX", "name": "INSAT 3B", "longitude": "81.2° E" },
  { "id": 51, "code": "BY", "name": "CTDRS", "longitude": "81.4° E" },
  { "id": 52, "code": "BZ", "name": "SUPERBIRD A", "longitude": "81.4° E" },
  { "id": 53, "code": "CA", "name": "INSAT 3D", "longitude": "82.1° E" },
  { "id": 54, "code": "CB", "name": "GSAT 6", "longitude": "82.5° E" },
  { "id": 55, "code": "CC", "name": "USA 65", "longitude": "82.6° E" },
  { "id": 56, "code": "CD", "name": "IRNSS 1C", "longitude": "82.8° E" },
  { "id": 57, "code": "CE", "name": "EKRAN 12", "longitude": "47.4° E" },
  { "id": 58, "code": "CF", "name": "CMS-02", "longitude": "83° E" },
  { "id": 59, "code": "CG", "name": "GSAT 30", "longitude": "83° E" },
  { "id": 60, "code": "CH", "name": "GSAT 10", "longitude": "83° E" },
  { "id": 61, "code": "CI", "name": "CMS-01", "longitude": "83.1° E" },
  { "id": 62, "code": "CJ", "name": "INMARSAT 6-F1", "longitude": "83.8° E" },
  { "id": 63, "code": "CK", "name": "BEIDOU G6", "longitude": "84° E" },
  { "id": 64, "code": "CL", "name": "ITALSAT 2", "longitude": "84.3° E" },
  { "id": 65, "code": "CM", "name": "TDRS 7", "longitude": "84.5° E" },
  { "id": 66, "code": "CN", "name": "USA 268", "longitude": "84.8° E" },
  { "id": 67, "code": "CO", "name": "EUTE 25A (HB 5)", "longitude": "84.9° E" },
  { "id": 68, "code": "CP", "name": "YAHSAT 1B", "longitude": "47.6° E" },
  { "id": 69, "code": "CQ", "name": "INTELSAT 15", "longitude": "85.1° E" },
  {
    "id": 70,
    "code": "CR",
    "name": "SIRIUS W (MARCOPOLO 1)",
    "longitude": "85.1° E"
  },
  { "id": 71, "code": "CS", "name": "GEOS 2", "longitude": "85.7° E" },
  {
    "id": 72,
    "code": "CT",
    "name": "EUROBIRD 4A(EUTELSAT W1)",
    "longitude": "85.8° E"
  },
  { "id": 73, "code": "CU", "name": "INSAT 1C", "longitude": "86.2° E" },
  { "id": 74, "code": "CV", "name": "THAICOM 5", "longitude": "86.4° E" },
  { "id": 75, "code": "CW", "name": "EKRAN 1", "longitude": "86.4° E" },
  { "id": 76, "code": "CX", "name": "KAZSAT 2", "longitude": "86.5° E" },
  { "id": 77, "code": "CY", "name": "EKRAN 9", "longitude": "86.8° E" },
  {
    "id": 78,
    "code": "CZ",
    "name": "SPACENET 4 (ASC 2)",
    "longitude": "87.1° E"
  },
  {
    "id": 79,
    "code": "DA",
    "name": "ABS-1A (KOREASAT 2)",
    "longitude": "47.7° E"
  },
  { "id": 80, "code": "DB", "name": "CHINASAT 15A", "longitude": "87.5° E" },
  { "id": 81, "code": "DC", "name": "EKRAN 6", "longitude": "87.7° E" },
  { "id": 82, "code": "DD", "name": "ST 2", "longitude": "88° E" },
  { "id": 83, "code": "DE", "name": "GOES 9", "longitude": "88.1° E" },
  { "id": 84, "code": "DF", "name": "BEIDOU IGSO 4", "longitude": "88.2° E" },
  {
    "id": 85,
    "code": "DG",
    "name": "WGS F4 (USA 233)",
    "longitude": "88.4° E"
  },
  { "id": 86, "code": "DH", "name": "TDRS 4", "longitude": "89.1° E" },
  { "id": 87, "code": "DI", "name": "SYMPHONIE 1", "longitude": "89.7° E" },
  { "id": 88, "code": "DJ", "name": "TDRS 8", "longitude": "89.8° E" },
  { "id": 89, "code": "DK", "name": "YAMAL 401", "longitude": "90° E" },
  { "id": 90, "code": "DL", "name": "GSAT 19", "longitude": "47.8° E" },
  { "id": 91, "code": "DM", "name": "INSAT 3C", "longitude": "90° E" },
  {
    "id": 92,
    "code": "DN",
    "name": "NSS 806 (INTELSAT 806)",
    "longitude": "90.3° E"
  },
  { "id": 93, "code": "DO", "name": "EXPRESS 4A", "longitude": "90.5° E" },
  { "id": 94, "code": "DP", "name": "TELECOM 1C", "longitude": "90.6° E" },
  { "id": 95, "code": "DQ", "name": "SICRAL 2", "longitude": "90.8° E" },
  { "id": 96, "code": "DR", "name": "MEASAT 3B", "longitude": "91.5° E" },
  { "id": 97, "code": "DS", "name": "MEASAT 3A", "longitude": "91.5° E" },
  { "id": 98, "code": "DT", "name": "MEASAT 3D", "longitude": "91.5° E" },
  { "id": 99, "code": "DU", "name": "STTW-1", "longitude": "91.8° E" },
  { "id": 100, "code": "DV", "name": "CHINASAT 9", "longitude": "92.1° E" },
  { "id": 101, "code": "DW", "name": "EXPRESS 2", "longitude": "49.2° E" },
  { "id": 102, "code": "DX", "name": "EXPRESS AM-3", "longitude": "92.3° E" },
  { "id": 103, "code": "DY", "name": "ANGOSAT 1", "longitude": "92.5° E" },
  { "id": 104, "code": "DZ", "name": "GALAXY 1R", "longitude": "92.5° E" },
  { "id": 105, "code": "EA", "name": "EUTELSAT 2-F4", "longitude": "93° E" },
  { "id": 106, "code": "EB", "name": "AMC-8 (GE-8)", "longitude": "93.3° E" },
  { "id": 107, "code": "EC", "name": "GARUDA 1", "longitude": "93.3° E" },
  { "id": 108, "code": "ED", "name": "GSAT 15", "longitude": "93.4° E" },
  { "id": 109, "code": "EE", "name": "GSAT 17", "longitude": "93.5° E" },
  {
    "id": 110,
    "code": "EF",
    "name": "AFRICASAT 1 (MEASAT 1)",
    "longitude": "93.6° E"
  },
  { "id": 111, "code": "EG", "name": "JCSAT 3", "longitude": "93.7° E" },
  { "id": 112, "code": "EH", "name": "TURKSAT 5B", "longitude": "42° E" },
  { "id": 113, "code": "EI", "name": "TURKSAT 4B", "longitude": "50° E" },
  { "id": 114, "code": "EJ", "name": "ASIASAT 3S", "longitude": "93.8° E" },
  { "id": 115, "code": "EK", "name": "LUCH 5V", "longitude": "94.8° E" },
  { "id": 116, "code": "EL", "name": "EXPRESS 2A", "longitude": "94.8° E" },
  { "id": 117, "code": "EM", "name": "SUPERBIRD A1", "longitude": "94.9° E" },
  { "id": 118, "code": "EN", "name": "SES-8", "longitude": "95° E" },
  { "id": 119, "code": "EO", "name": "SES 12", "longitude": "95° E" },
  { "id": 120, "code": "EP", "name": "RADUGA 1M-1", "longitude": "95.1° E" },
  { "id": 121, "code": "EQ", "name": "SKYNET 5A", "longitude": "95.2° E" },
  { "id": 122, "code": "ER", "name": "AMOS 5", "longitude": "95.7° E" },
  { "id": 123, "code": "ES", "name": "GSAT 9", "longitude": "97.3° E" },
  {
    "id": 124,
    "code": "ET",
    "name": "INTELSAT 26 (JCSAT 4)",
    "longitude": "50.8° E"
  },
  { "id": 125, "code": "EU", "name": "RADUGA 1-5", "longitude": "97.5° E" },
  { "id": 126, "code": "EV", "name": "CHINASAT 11", "longitude": "97.9° E" },
  { "id": 127, "code": "EW", "name": "CHINASAT 2E", "longitude": "98.1° E" },
  { "id": 128, "code": "EX", "name": "CHINASAT 2A", "longitude": "98.3° E" },
  { "id": 129, "code": "EY", "name": "THURAYA 3", "longitude": "98.5° E" },
  { "id": 130, "code": "EZ", "name": "USA 143", "longitude": "98.6° E" },
  { "id": 131, "code": "FA", "name": "TURKSAT 1C", "longitude": "99.1° E" },
  { "id": 132, "code": "FB", "name": "JCSAT 1", "longitude": "99.2° E" },
  {
    "id": 133,
    "code": "FC",
    "name": "EUTELSAT 1-F5 (ECS 5)",
    "longitude": "99.2° E"
  },
  {
    "id": 134,
    "code": "FD",
    "name": "DIRECTV 2 (DBS 2)",
    "longitude": "99.2° E"
  },
  { "id": 135, "code": "FE", "name": "BELINTERSAT 1", "longitude": "51.5° E" },
  {
    "id": 136,
    "code": "FF",
    "name": "DIRECTV 6 (TEMPO 2)",
    "longitude": "99.9° E"
  },
  { "id": 137, "code": "FG", "name": "MEASAT 2", "longitude": "100.1° E" },
  { "id": 138, "code": "FH", "name": "STTW-3", "longitude": "100.1° E" },
  { "id": 139, "code": "FI", "name": "ASIASAT 5", "longitude": "100.5° E" },
  { "id": 140, "code": "FJ", "name": "NIGCOMSAT 1", "longitude": "102.9° E" },
  { "id": 141, "code": "FK", "name": "ANIK E2", "longitude": "103.1° E" },
  {
    "id": 142,
    "code": "FL",
    "name": "CHINASAT 2C (ZX 2C)",
    "longitude": "103.4° E"
  },
  {
    "id": 143,
    "code": "FM",
    "name": "DIRECTV 1 (DBS 1)",
    "longitude": "103.4° E"
  },
  { "id": 144, "code": "FN", "name": "PAS 1", "longitude": "103.8° E" },
  { "id": 145, "code": "FO", "name": "YURI (BSE)", "longitude": "104.1° E" },
  { "id": 146, "code": "FP", "name": "IRNSS-1A", "longitude": "51.6° E" },
  { "id": 147, "code": "FQ", "name": "FENGYUN 4A", "longitude": "104.7° E" },
  { "id": 148, "code": "FR", "name": "MARISAT 3", "longitude": "105.1° E" },
  { "id": 149, "code": "FS", "name": "COSMOS 2224", "longitude": "105.1° E" },
  { "id": 150, "code": "FT", "name": "ASIASTAR", "longitude": "105.2° E" },
  { "id": 151, "code": "FU", "name": "ASIASAT 7", "longitude": "105.5° E" },
  { "id": 152, "code": "FV", "name": "INTELSAT 511", "longitude": "105.5° E" },
  { "id": 153, "code": "FW", "name": "GOES 7", "longitude": "105.6° E" },
  { "id": 154, "code": "FX", "name": "GAOFEN 4", "longitude": "105.7° E" },
  { "id": 155, "code": "FY", "name": "BEIDOU IGSO 2", "longitude": "106.6° E" },
  { "id": 156, "code": "FZ", "name": "RADUGA 1-4", "longitude": "107.4° E" },
  { "id": 157, "code": "GA", "name": "SATCOM 3R", "longitude": "113.9° E" },
  { "id": 158, "code": "GB", "name": "ASTRA 1C", "longitude": "114° E" },
  {
    "id": 159,
    "code": "GC",
    "name": "SJ-17 (SHIJIAN-17)",
    "longitude": "115.4° E"
  },
  { "id": 160, "code": "GD", "name": "CHINASAT 6B", "longitude": "115.5° E" },
  { "id": 161, "code": "GE", "name": "KOREASAT 7", "longitude": "115.9° E" },
  { "id": 162, "code": "GF", "name": "KOREASAT 6", "longitude": "116° E" },
  { "id": 163, "code": "GG", "name": "GALAXY 1", "longitude": "118° E" },
  { "id": 164, "code": "GH", "name": "IRNSS 1B", "longitude": "52.3° E" },
  { "id": 165, "code": "GI", "name": "TELKOM 3S", "longitude": "118° E" },
  { "id": 166, "code": "GJ", "name": "DIRECTV 1R", "longitude": "119.2° E" },
  { "id": 167, "code": "GK", "name": "IPSTAR 1", "longitude": "119.5° E" },
  { "id": 168, "code": "GL", "name": "SATCOM C3", "longitude": "119.5° E" },
  { "id": 169, "code": "GM", "name": "EXPRESS AM-1", "longitude": "119.7° E" },
  { "id": 170, "code": "GN", "name": "BEIDOU IGSO 3", "longitude": "119.8° E" },
  { "id": 171, "code": "GO", "name": "ASIASAT 6", "longitude": "119.9° E" },
  { "id": 172, "code": "GP", "name": "COMSTAR 1", "longitude": "121.5° E" },
  { "id": 173, "code": "GQ", "name": "BRAZILSAT 1", "longitude": "121.6° E" },
  { "id": 174, "code": "GR", "name": "ASIASAT 9", "longitude": "122.1° E" },
  { "id": 175, "code": "GS", "name": "YAHSAT 1A", "longitude": "52.5° E" },
  { "id": 176, "code": "GT", "name": "ETS 8", "longitude": "122.4° E" },
  { "id": 177, "code": "GU", "name": "INTELSAT 802", "longitude": "123.5° E" },
  { "id": 178, "code": "GV", "name": "TELECOM 2B", "longitude": "123.6° E" },
  { "id": 179, "code": "GW", "name": "NSTAR C", "longitude": "123.6° E" },
  { "id": 180, "code": "GX", "name": "ESA/GOES", "longitude": "123.6° E" },
  { "id": 181, "code": "GY", "name": "JCSAT 13", "longitude": "124° E" },
  { "id": 182, "code": "GZ", "name": "INTELSAT 603", "longitude": "124.1° E" },
  {
    "id": 183,
    "code": "HA",
    "name": "FLTSATCOM 8 (USA 46)",
    "longitude": "124.7° E"
  },
  { "id": 184, "code": "HB", "name": "CHINASAT-26", "longitude": "125.1° E" },
  {
    "id": 185,
    "code": "HC",
    "name": "SAKURA 2A (CS-2A)",
    "longitude": "125.3° E"
  },
  { "id": 186, "code": "HD", "name": "COSMOS 1897", "longitude": "52.6° E" },
  { "id": 187, "code": "HE", "name": "INTELSAT 907", "longitude": "125.6° E" },
  {
    "id": 188,
    "code": "HF",
    "name": "TELSTAR 12 (ORION 2)",
    "longitude": "126° E"
  },
  { "id": 189, "code": "HG", "name": "DFH-3 2", "longitude": "126.1° E" },
  { "id": 190, "code": "HH", "name": "CHINASAT 22", "longitude": "126.1° E" },
  { "id": 191, "code": "HI", "name": "CHINASAT 6A", "longitude": "126.6° E" },
  {
    "id": 192,
    "code": "HJ",
    "name": "QZS-3 (MICHIBIKI-3)",
    "longitude": "127° E"
  },
  {
    "id": 193,
    "code": "HK",
    "name": "USA 257 (CLIO)",
    "longitude": "127.1° E"
  },
  {
    "id": 194,
    "code": "HL",
    "name": "OPS 0757 (TACSAT)",
    "longitude": "127.7° E"
  },
  { "id": 195, "code": "HM", "name": "JCSAT 10", "longitude": "128° E" },
  { "id": 196, "code": "HN", "name": "RADUGA 29", "longitude": "128° E" },
  { "id": 197, "code": "HO", "name": "TURKSAT 4A", "longitude": "42° E" },
  { "id": 198, "code": "HP", "name": "SKYNET 5D", "longitude": "52.7° E" },
  { "id": 199, "code": "HQ", "name": "COMS 1", "longitude": "128.2° E" },
  {
    "id": 200,
    "code": "HR",
    "name": "GEO-KOMPSAT-2A",
    "longitude": "128.2° E"
  },
  {
    "id": 201,
    "code": "HS",
    "name": "GEO-KOMPSAT-2B",
    "longitude": "128.3° E"
  },
  { "id": 202, "code": "HT", "name": "LAOSAT 1", "longitude": "128.5° E" },
  { "id": 203, "code": "HU", "name": "IRNSS 1G", "longitude": "129.5° E" },
  { "id": 204, "code": "HV", "name": "CHINASAT 6C", "longitude": "130.2° E" },
  {
    "id": 205,
    "code": "HW",
    "name": "FLTSATCOM 7 (USA 20)",
    "longitude": "130.4° E"
  },
  {
    "id": 206,
    "code": "HX",
    "name": "HIMAWARI 3 (GMS 3)",
    "longitude": "130.7° E"
  },
  { "id": 207, "code": "HY", "name": "HISPASAT 1A", "longitude": "130.7° E" },
  { "id": 208, "code": "HZ", "name": "OPS 7641", "longitude": "131.5° E" },
  { "id": 209, "code": "IA", "name": "EXPRESS AM-6", "longitude": "53° E" },
  { "id": 210, "code": "IB", "name": "VINASAT 2", "longitude": "131.8° E" },
  { "id": 211, "code": "IC", "name": "VINASAT 1", "longitude": "131.9° E" },
  { "id": 212, "code": "ID", "name": "JCSAT 12", "longitude": "132° E" },
  { "id": 213, "code": "IE", "name": "COSMOS 2379", "longitude": "132° E" },
  { "id": 214, "code": "IF", "name": "JCSAT 9", "longitude": "132.1° E" },
  { "id": 215, "code": "IG", "name": "JCSAT 8", "longitude": "132.4° E" },
  {
    "id": 216,
    "code": "IH",
    "name": "OPS 9381 (GGTS)",
    "longitude": "132.8° E"
  },
  { "id": 217, "code": "II", "name": "BEIDOU G2", "longitude": "134° E" },
  { "id": 218, "code": "IJ", "name": "APSTAR 6C", "longitude": "134° E" },
  { "id": 219, "code": "IK", "name": "JCSAT 16", "longitude": "134.4° E" },
  { "id": 220, "code": "IL", "name": "ORION 3", "longitude": "53° E" },
  { "id": 221, "code": "IM", "name": "DIRECTV 4S", "longitude": "135.7° E" },
  { "id": 222, "code": "IN", "name": "JCSAT 17", "longitude": "135.9° E" },
  { "id": 223, "code": "IO", "name": "ELEKTRO-L", "longitude": "136.1° E" },
  { "id": 224, "code": "IP", "name": "THOR 2A", "longitude": "136.4° E" },
  { "id": 225, "code": "IQ", "name": "INMARSAT 2-F1", "longitude": "137.7° E" },
  { "id": 226, "code": "IR", "name": "INSAT 2A", "longitude": "137.8° E" },
  { "id": 227, "code": "IS", "name": "TELSTAR 18V", "longitude": "138° E" },
  { "id": 228, "code": "IT", "name": "INMARSAT 2-F2", "longitude": "138.9° E" },
  { "id": 229, "code": "IU", "name": "TURKSAT 2A", "longitude": "139.1° E" },
  { "id": 230, "code": "IV", "name": "EXPRESS AT-2", "longitude": "139.9° E" },
  { "id": 231, "code": "IW", "name": "SUPERBIRD C", "longitude": "53.2° E" },
  { "id": 232, "code": "IX", "name": "EXPRESS-AM5", "longitude": "140° E" },
  { "id": 233, "code": "IY", "name": "SKYNET 2B", "longitude": "140.1° E" },
  { "id": 234, "code": "IZ", "name": "SKY MUSTER", "longitude": "140.2° E" },
  {
    "id": 235,
    "code": "JA",
    "name": "NSS 5 (INTELSAT 803)",
    "longitude": "151° E"
  },
  {
    "id": 236,
    "code": "JB",
    "name": "TELSTAR 11 (ORION 1)",
    "longitude": "151° E"
  },
  { "id": 237, "code": "JC", "name": "EKRAN 8", "longitude": "151.5° E" },
  { "id": 238, "code": "JD", "name": "YAMAL 402", "longitude": "54.9° E" },
  { "id": 239, "code": "JE", "name": "OPTUS D1", "longitude": "152° E" },
  { "id": 240, "code": "JF", "name": "USA 169", "longitude": "152.4° E" },
  { "id": 241, "code": "JG", "name": "MORELOS 2", "longitude": "152.7° E" },
  {
    "id": 242,
    "code": "JH",
    "name": "HIMAWARI 1 (GMS 1)",
    "longitude": "153.2° E"
  },
  { "id": 243, "code": "JI", "name": "EKRAN 14", "longitude": "153.5° E" },
  { "id": 244, "code": "JJ", "name": "JCSAT-14", "longitude": "154° E" },
  { "id": 245, "code": "JK", "name": "TJS-1", "longitude": "155° E" },
  { "id": 246, "code": "JL", "name": "ABS 3", "longitude": "155.5° E" },
  { "id": 247, "code": "JM", "name": "OPTUS C1", "longitude": "155.7° E" },
  { "id": 248, "code": "JN", "name": "AMC-7 (GE-7)", "longitude": "156° E" },
  { "id": 249, "code": "JO", "name": "GSAT 16", "longitude": "55° E" },
  { "id": 250, "code": "JP", "name": "OPTUS 10", "longitude": "156° E" },
  { "id": 251, "code": "JQ", "name": "OPTUS D3", "longitude": "156° E" },
  { "id": 252, "code": "JR", "name": "BEIDOU 1", "longitude": "156.2° E" },
  {
    "id": 253,
    "code": "JS",
    "name": "INTELSAT 1R (PAS 1R)",
    "longitude": "157.1° E"
  },
  { "id": 254, "code": "JT", "name": "JCSAT 2", "longitude": "157.3° E" },
  { "id": 255, "code": "JU", "name": "TURKSAT 1B", "longitude": "157.5° E" },
  { "id": 256, "code": "JV", "name": "HISPASAT 1D", "longitude": "157.8° E" },
  {
    "id": 257,
    "code": "JW",
    "name": "GSAT 3 (EDUSAT)",
    "longitude": "158.9° E"
  },
  { "id": 258, "code": "JX", "name": "ABS 1 (LMI 1)", "longitude": "159° E" },
  { "id": 259, "code": "JY", "name": "GALAXY 2", "longitude": "159.3° E" },
  { "id": 260, "code": "JZ", "name": "GSAT 29", "longitude": "55.1° E" },
  { "id": 261, "code": "KA", "name": "OPTUS D2", "longitude": "160° E" },
  { "id": 262, "code": "KB", "name": "BEIDOU G4", "longitude": "160° E" },
  { "id": 263, "code": "KC", "name": "GALAXY 5", "longitude": "163.1° E" },
  { "id": 264, "code": "KD", "name": "WESTAR 5", "longitude": "163.2° E" },
  { "id": 265, "code": "KE", "name": "ARABSAT 2A", "longitude": "163.3° E" },
  { "id": 266, "code": "KF", "name": "YAMAL 202", "longitude": "163.5° E" },
  { "id": 267, "code": "KG", "name": "EKRAN 10", "longitude": "164.2° E" },
  {
    "id": 268,
    "code": "KH",
    "name": "INTELSAT 5 (PAS 5)",
    "longitude": "165.9° E"
  },
  { "id": 269, "code": "KI", "name": "INTELSAT 19", "longitude": "166° E" },
  {
    "id": 270,
    "code": "KJ",
    "name": "EUTE 33A (EB 3)",
    "longitude": "166.2° E"
  },
  { "id": 271, "code": "KK", "name": "GSAT 8", "longitude": "55.1° E" },
  { "id": 272, "code": "KL", "name": "SYNCOM 3", "longitude": "166.6° E" },
  { "id": 273, "code": "KM", "name": "SBS 1", "longitude": "167.1° E" },
  { "id": 274, "code": "KN", "name": "TIANLIAN 1-02", "longitude": "167.1° E" },
  { "id": 275, "code": "KO", "name": "LUCH 5A", "longitude": "167.2° E" },
  { "id": 276, "code": "KP", "name": "KOREASAT 1", "longitude": "167.8° E" },
  { "id": 277, "code": "KQ", "name": "AMC-5 (GE-5)", "longitude": "168° E" },
  { "id": 278, "code": "KR", "name": "INMARSAT 3-F2", "longitude": "169.5° E" },
  {
    "id": 279,
    "code": "KS",
    "name": "METEOSAT 5 (MOP 2)",
    "longitude": "170.2° E"
  },
  { "id": 280, "code": "KT", "name": "EUTELSAT 172B", "longitude": "172° E" },
  { "id": 281, "code": "KU", "name": "GE-23", "longitude": "174° E" },
  { "id": 282, "code": "KV", "name": "NIGCOMSAT 1R", "longitude": "42.5° E" },
  { "id": 283, "code": "KW", "name": "STTW-4", "longitude": "55.7° E" },
  { "id": 284, "code": "KX", "name": "BSAT-1B", "longitude": "174.6° E" },
  { "id": 285, "code": "KY", "name": "LES 5", "longitude": "174.9° E" },
  { "id": 286, "code": "KZ", "name": "NSS 11 (AAP-1)", "longitude": "176° E" },
  { "id": 287, "code": "LA", "name": "TIANLIAN 1-04", "longitude": "176.6° E" },
  { "id": 288, "code": "LB", "name": "AMC-1 (GE-1)", "longitude": "176.6° E" },
  {
    "id": 289,
    "code": "LC",
    "name": "INTELSAT 10 (PAS 10)",
    "longitude": "177.7° E"
  },
  { "id": 290, "code": "LD", "name": "INTELSAT 707", "longitude": "178.1° E" },
  { "id": 291, "code": "LE", "name": "SUPERBIRD 6", "longitude": "178.9° E" },
  { "id": 292, "code": "LF", "name": "INMARSAT 5-F3", "longitude": "179.6° E" },
  { "id": 293, "code": "LG", "name": "CHINASAT 22A", "longitude": "179.7° E" },
  { "id": 294, "code": "LH", "name": "EXPRESS AT-1", "longitude": "56° E" },
  { "id": 295, "code": "LI", "name": "TELECOM 1A", "longitude": "180° E" },
  { "id": 296, "code": "LJ", "name": "INMARSAT 5-F4", "longitude": "56.5° E" },
  { "id": 297, "code": "LK", "name": "SPACENET 2", "longitude": "56.6° E" },
  { "id": 298, "code": "LL", "name": "NSS 12", "longitude": "57° E" },
  { "id": 299, "code": "LM", "name": "ASTRA 2A", "longitude": "57.1° E" },
  { "id": 300, "code": "LN", "name": "EKRAN 11", "longitude": "57.3° E" },
  {
    "id": 301,
    "code": "LO",
    "name": "WGS F2 (USA 204)",
    "longitude": "57.5° E"
  },
  { "id": 302, "code": "LP", "name": "NILESAT 102", "longitude": "58° E" },
  { "id": 303, "code": "LQ", "name": "COSMOS 1700", "longitude": "58° E" },
  { "id": 304, "code": "LR", "name": "GALAXY 4R", "longitude": "44° E" },
  { "id": 305, "code": "LS", "name": "EKRAN 4", "longitude": "58.1° E" },
  { "id": 306, "code": "LT", "name": "OPS 9454", "longitude": "58.1° E" },
  {
    "id": 307,
    "code": "LU",
    "name": "ECHOSTAR 12 (RAINBOW 1)",
    "longitude": "58.3° E"
  },
  { "id": 308, "code": "LV", "name": "KAZSAT 3", "longitude": "58.5° E" },
  { "id": 309, "code": "LW", "name": "STTW-T1", "longitude": "58.7° E" },
  { "id": 310, "code": "LX", "name": "OPS 9751", "longitude": "59.3° E" },
  { "id": 311, "code": "LY", "name": "AURORA 2", "longitude": "59.4° E" },
  { "id": 312, "code": "LZ", "name": "ARTEMIS", "longitude": "59.7° E" },
  { "id": 313, "code": "MA", "name": "INTELSAT 33E", "longitude": "60° E" },
  {
    "id": 314,
    "code": "MB",
    "name": "WGS 10 (USA 291)",
    "longitude": "60.3° E"
  },
  { "id": 315, "code": "MC", "name": "THURAYA 2", "longitude": "44.1° E" },
  { "id": 316, "code": "MD", "name": "MBSAT", "longitude": "61° E" },
  { "id": 317, "code": "ME", "name": "EUTELSAT 2-F3", "longitude": "61.3° E" },
  { "id": 318, "code": "MF", "name": "GOES 13", "longitude": "61.4° E" },
  { "id": 319, "code": "MG", "name": "INTELSAT 39", "longitude": "61.9° E" },
  { "id": 320, "code": "MH", "name": "USA 252", "longitude": "62.3° E" },
  { "id": 321, "code": "MI", "name": "JCSAT 5", "longitude": "62.6° E" },
  { "id": 322, "code": "MJ", "name": "INMARSAT 5-F1", "longitude": "62.6° E" },
  { "id": 323, "code": "MK", "name": "PAS 6", "longitude": "62.8° E" },
  { "id": 324, "code": "ML", "name": "YAMAL 201", "longitude": "63° E" },
  { "id": 325, "code": "MM", "name": "COMSATBW-1", "longitude": "63° E" },
  {
    "id": 326,
    "code": "MN",
    "name": "BLAGOVEST 11L (COSMOS 2520)",
    "longitude": "45° E"
  },
  { "id": 327, "code": "MO", "name": "ECHOSTAR 5", "longitude": "63.7° E" },
  { "id": 328, "code": "MP", "name": "INMARSAT 4-F2", "longitude": "63.9° E" },
  { "id": 329, "code": "MQ", "name": "INSAT 1A", "longitude": "64° E" },
  { "id": 330, "code": "MR", "name": "INTELSAT 906", "longitude": "64.1° E" },
  { "id": 331, "code": "MS", "name": "STTW-2", "longitude": "64.2° E" },
  { "id": 332, "code": "MT", "name": "GSAT 1", "longitude": "64.4° E" },
  { "id": 333, "code": "MU", "name": "ECHOSTAR 8", "longitude": "64.5° E" },
  { "id": 334, "code": "MV", "name": "OPS 5346", "longitude": "64.8° E" },
  { "id": 335, "code": "MW", "name": "AMOS-4", "longitude": "65° E" },
  {
    "id": 336,
    "code": "MX",
    "name": "NEWSAT-1 (PALAPA B2R)",
    "longitude": "65.1° E"
  },
  {
    "id": 337,
    "code": "MY",
    "name": "AZERSPACE 2/INTELSAT 38",
    "longitude": "45.1° E"
  },
  { "id": 338, "code": "MZ", "name": "SICRAL 1B", "longitude": "65.2° E" },
  { "id": 339, "code": "NA", "name": "MSAT M1", "longitude": "65.7° E" },
  {
    "id": 340,
    "code": "NB",
    "name": "SBIRS GEO 1 (USA 230)",
    "longitude": "65.7° E"
  },
  { "id": 341, "code": "NC", "name": "INTELSAT 17", "longitude": "66° E" },
  { "id": 342, "code": "ND", "name": "TJS-2", "longitude": "66.6° E" },
  { "id": 343, "code": "NE", "name": "KUPON", "longitude": "66.8° E" },
  { "id": 344, "code": "NF", "name": "COSMOS 1366", "longitude": "67.5° E" },
  { "id": 345, "code": "NG", "name": "INSAT 4CR", "longitude": "67.5° E" },
  { "id": 346, "code": "NH", "name": "SUPERBIRD 4", "longitude": "67.8° E" },
  {
    "id": 347,
    "code": "NI",
    "name": "ANIK A2 (TELESAT 2)",
    "longitude": "68.4° E"
  },
  { "id": 348, "code": "NJ", "name": "NATO 3D", "longitude": "45.6° E" },
  { "id": 349, "code": "NK", "name": "TVSAT 2", "longitude": "68.4° E" },
  { "id": 350, "code": "NL", "name": "INTELSAT 20", "longitude": "68.5° E" },
  { "id": 351, "code": "NM", "name": "INTELSAT 36", "longitude": "68.5° E" },
  { "id": 352, "code": "NN", "name": "ELEKTRO (GOMS)", "longitude": "69.3° E" },
  { "id": 353, "code": "NO", "name": "INSAT 1D", "longitude": "70.1° E" },
  {
    "id": 354,
    "code": "NP",
    "name": "USA 250 (NROL-67)",
    "longitude": "70.1° E"
  },
  { "id": 355, "code": "NQ", "name": "EUTE 70B", "longitude": "70.5° E" },
  { "id": 356, "code": "NR", "name": "INSAT 1B", "longitude": "70.7° E" },
  { "id": 357, "code": "NS", "name": "EKRAN 2", "longitude": "70.7° E" },
  { "id": 358, "code": "NT", "name": "INTELSAT 29E", "longitude": "71.1° E" }
]
