version: "3"

name: frontend
services:
  ui:
    build:
      network: host
      context: ../
      dockerfile: docker/nextjs/Dockerfile
    image: signal-process-system-frontend
    restart: always
    env_file:
      - ../.env.production
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway
      - docker.host:192.168.16.31

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: signal_processing_system
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./nextjs/initdb.d/:/docker-entrypoint-initdb.d/

  db-viewer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5433:8080

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ui
