version: "3"

name: frontend
services:
  nextjs:
    build:
      context: ../
      dockerfile: docker/nextjs/Dockerfile
    image: signal-process-system-frontend
    container_name: nextjs
    restart: always
    env_file:
      - ../.env.production
    ports:
      - 3009:3000

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: signal_processing_system
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./nextjs/initdb.d/:/docker-entrypoint-initdb.d/

  db-viewer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5433:8080
