version: "3"

# name: frontend
services:
  nextjs:
    build:
      context: ../
      dockerfile: nextjs-docker/nextjs/Dockerfile
    image: signal-process-system-frontend
    container_name: nextjs
    networks:
      - frontend
      - mongo
    restart: always
    env_file:
      - ../.env.production
    volumes:
      - nfs_mongo_files:/app/public/files:rw

networks:
  frontend:
    name: frontend
  mongo:
    external:
      name: mongodb

volumes:
  nfs_mongo_files:
    name: nfs_mongo_files
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.16.61,nolock,soft,rw,nfsvers=3
      device: ":/mnt/remote_storage/frontend/files"
