version: "3"

# name: frontend
services:
  nextjs:
    build:
      context: ../
      dockerfile: nextjs-docker/nextjs/Dockerfile
    image: signal-process-system-frontend
    container_name: nextjs
    networks:
      - mongo
    restart: always
    env_file:
      - ../.env.production
    volumes:
      - /mnt/iscsi_frontend/files:/app/public/mount:rw

networks:
  mongo:
    external:
      name: mongo-replica-set_mongodb
