version: "3"

# name: frontend
services:
  nextjs:
    build:
      context: ../
      dockerfile: nextjs-docker/nextjs/Dockerfile
    image: signal-process-system-frontend
    container_name: nextjs
    networks:
      - frontend
      - mongo
    restart: always
    env_file:
      - ../.env.production

networks:
  frontend:
  mongo:
    exteral:
      name: mongo-replica-set_mongodb
